// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEmNtSP6vaNU3p4acQAGVk0LxmcnejH-I',
    appId: '1:741287059658:web:4312a4e0e6d8a609f8d433',
    messagingSenderId: '741287059658',
    projectId: 'mise-23967',
    authDomain: 'mise-23967.firebaseapp.com',
    storageBucket: 'mise-23967.firebasestorage.app',
    measurementId: 'G-7Y936EG2VD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP3LMYBtfWMVkTWIK3qXluBBPan98O3zw',
    appId: '1:741287059658:android:b7f39491ed527869f8d433',
    messagingSenderId: '741287059658',
    projectId: 'mise-23967',
    storageBucket: 'mise-23967.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4zno8OoajXitBNQdbou0T4yROie6-68E',
    appId: '1:741287059658:ios:b78ed78a1db4c277f8d433',
    messagingSenderId: '741287059658',
    projectId: 'mise-23967',
    storageBucket: 'mise-23967.firebasestorage.app',
    iosBundleId: 'com.example.mise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4zno8OoajXitBNQdbou0T4yROie6-68E',
    appId: '1:741287059658:ios:b78ed78a1db4c277f8d433',
    messagingSenderId: '741287059658',
    projectId: 'mise-23967',
    storageBucket: 'mise-23967.firebasestorage.app',
    iosBundleId: 'com.example.mise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEmNtSP6vaNU3p4acQAGVk0LxmcnejH-I',
    appId: '1:741287059658:web:4a90233671c4b4e1f8d433',
    messagingSenderId: '741287059658',
    projectId: 'mise-23967',
    authDomain: 'mise-23967.firebaseapp.com',
    storageBucket: 'mise-23967.firebasestorage.app',
    measurementId: 'G-0R6BW0XK5D',
  );

}